---
# tasks file for /Users/carlosfrias/apigee-workspace/opdk-workspace/apigee-opdk-setup-message-processor-bind-environment
- name: Bind message processor to environment {{ env_name }}
  uri:
    user: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'
    method: POST
    body: action=add&uuid={{ edge_mp_self.uUID }}
    url: http://{{ local_mgmt_ip }}:8080/v1/o/{{ org_name }}/e/{{ env_name }}

